# Generated by Django 5.0.4 on 2025-12-29 11:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("edupace_app", "0002_add_assessment_models"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="grade",
            options={
                "ordering": [
                    "-academic_year",
                    "-semester",
                    "course",
                    "assessment_type",
                ],
                "verbose_name": "Grade",
                "verbose_name_plural": "Grades",
            },
        ),
        migrations.AlterUniqueTogether(
            name="grade",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="grade",
            name="assessment_type",
            field=models.CharField(
                choices=[
                    ("midterm", "Midterm"),
                    ("assignment", "Assignment"),
                    ("project", "Project"),
                    ("final", "Final"),
                ],
                default="final",
                help_text="Type of assessment (Midterm, Assignment, Project, Final)",
                max_length=20,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="grade",
            unique_together={
                ("student", "course", "assessment_type", "semester", "academic_year")
            },
        ),
    ]
